# Generated by Django 4.0.6 on 2022-07-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_roadmapitem_alt_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapCarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "roadmap_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.roadmapitem",
                    ),
                ),
            ],
        ),
    ]
