# Generated by Django 4.0.6 on 2022-07-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_roadmapcarouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapitem",
            name="alt_names",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
