# Generated by Django 4.0.6 on 2022-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_roadmapitem_alt_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapcarouselimage",
            name="image",
            field=models.ImageField(upload_to="roadmap-carousel"),
        ),
        migrations.AlterField(
            model_name="roadmapitem",
            name="thumbnail",
            field=models.ImageField(upload_to="roadmap-thumbnails"),
        ),
    ]
