# Generated by Django 4.0.6 on 2022-07-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_roadmapcarouselimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapcarouselimage",
            name="roadmap_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carousel_images",
                to="base.roadmapitem",
            ),
        ),
    ]
