# Generated by Django 4.1 on 2022-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_roadmapcarouselimage_roadmap_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapitem",
            name="block_id",
            field=models.CharField(max_length=100),
        ),
    ]
